org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
## Keep legacy DSL for Flutter Gradle plugin compatibility
android.newDsl=false
## Temporarily keep this false while migrating plugins to built-in Kotlin
android.builtInKotlin=false
