plugins {
    id("com.android.application")
    // The Flutter Gradle Plugin must be applied after the Android Gradle plugin.
    id("dev.flutter.flutter-gradle-plugin")
}

android {
    namespace = "com.example.rpg_catalog"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "com.example.rpg_catalog"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig = signingConfigs.getByName("debug")
        }
    }
}

flutter {
    source = "../.."
}

// Replace GeneratedPluginRegistrant with a reflection-based version before Java
// compilation so builds don't fail if plugin classes aren't visible at compile
// time. This runs every build and is safe because the generated file is
// regenerated by Flutter; we overwrite it with a resilient wrapper.
// Let Flutter generate `GeneratedPluginRegistrant.java` and avoid custom overrides.


val replaceGeneratedPluginRegistrant by tasks.registering {
        doLast {
                val genFile = file("src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java")
                genFile.parentFile.mkdirs()
                genFile.writeText("""
package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
    private static final String TAG = "GeneratedPluginRegistrant";
    public static void registerWith(@NonNull FlutterEngine flutterEngine) {
        try {
            try {
                Class<?> cls = Class.forName("com.mr.flutter.plugin.filepicker.FilePickerPlugin");
                Object plugin = cls.getDeclaredConstructor().newInstance();
                flutterEngine.getPlugins().add((io.flutter.embedding.engine.plugins.FlutterPlugin) plugin);
            } catch (ClassNotFoundException cnfe) {
                Log.w(TAG, "Plugin class com.mr.flutter.plugin.filepicker.FilePickerPlugin not found, skipping registration.");
            }
        } catch (Exception e) {
            Log.e(TAG, "Error registering plugin file_picker via reflection", e);
        }
        try {
            try {
                Class<?> cls = Class.forName("com.baseflow.permissionhandler.PermissionHandlerPlugin");
                Object plugin = cls.getDeclaredConstructor().newInstance();
                flutterEngine.getPlugins().add((io.flutter.embedding.engine.plugins.FlutterPlugin) plugin);
            } catch (ClassNotFoundException cnfe) {
                Log.w(TAG, "Plugin class com.baseflow.permissionhandler.PermissionHandlerPlugin not found, skipping registration.");
            }
        } catch (Exception e) {
            Log.e(TAG, "Error registering plugin permission_handler via reflection", e);
        }
        try {
            try {
                Class<?> cls = Class.forName("dev.steenbakker.mobile_scanner.MobileScannerPlugin");
                Object plugin = cls.getDeclaredConstructor().newInstance();
                flutterEngine.getPlugins().add((io.flutter.embedding.engine.plugins.FlutterPlugin) plugin);
            } catch (ClassNotFoundException cnfe) {
                Log.w(TAG, "Plugin class dev.steenbakker.mobile_scanner.MobileScannerPlugin not found, skipping registration.");
            }
        } catch (Exception e) {
            Log.e(TAG, "Error registering plugin mobile_scanner via reflection", e);
        }
        try {
            flutterEngine.getPlugins().add(new io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin());
        } catch (Exception e) {
            Log.e(TAG, "Error registering plugin flutter_plugin_android_lifecycle, io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin", e);
        }
        try {
            flutterEngine.getPlugins().add(new com.github.dart_lang.jni.JniPlugin());
        } catch (Exception e) {
            Log.e(TAG, "Error registering plugin jni, com.github.dart_lang.jni.JniPlugin", e);
        }
        try {
            flutterEngine.getPlugins().add(new com.github.dart_lang.jni_flutter.JniFlutterPlugin());
        } catch (Exception e) {
            Log.e(TAG, "Error registering plugin jni_flutter, com.github.dart_lang.jni_flutter.JniFlutterPlugin", e);
        }
        try {
            flutterEngine.getPlugins().add(new io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin());
        } catch (Exception e) {
            Log.e(TAG, "Error registering plugin shared_preferences_android, io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin", e);
        }
        try {
            flutterEngine.getPlugins().add(new com.tekartik.sqflite.SqflitePlugin());
        } catch (Exception e) {
            Log.e(TAG, "Error registering plugin sqflite_android, com.tekartik.sqflite.SqflitePlugin", e);
        }
    }
}
""")
        }
}

tasks.withType(org.gradle.api.tasks.compile.JavaCompile::class.java) {
    dependsOn(replaceGeneratedPluginRegistrant)
}
